// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqn7q70QApaDwfQAHHWAE6g8rZEdvCbVM',
    appId: '1:805440400995:web:9f9e54efdaf4bfedadd256',
    messagingSenderId: '805440400995',
    projectId: 'sonictouchdata',
    authDomain: 'sonictouchdata.firebaseapp.com',
    storageBucket: 'sonictouchdata.firebasestorage.app',
    measurementId: 'G-7CNGBF9JWM',
    databaseURL: 'https://sonictouchdata-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsbtzp50d0h6O4N7MPhlFkWuURngMHcYQ',
    appId: '1:805440400995:android:8d0a890f81829e23add256',
    messagingSenderId: '805440400995',
    projectId: 'sonictouchdata',
    storageBucket: 'sonictouchdata.firebasestorage.app',
    databaseURL: 'https://sonictouchdata-default-rtdb.firebaseio.com',
  );
}
